services: 
  anki-desktop: 
    build: 
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ~/.local/share/Anki2:/config/app/Anki2
      - ~/backups:/config/app/backups
    ports: 
      - 3500:3500
      # Anki Connect port
      - 8765:8765
